import type { Metadata } from "next";
import "@/styles/font.css";
import "@/styles/globals.css";
import 'swiper/css';
import "swiper/css/navigation";
import PWAUpdater from "@/components/system/PWAUpdater"
import AppVersionChecker from "@/components/system/AppVersionChecker"
import ThemeWrapper from "@/components/system/ThemeWrapper";
import {Toaster} from "react-hot-toast";
import FetchUserClient from "@/components/system/FetchUserClient";

export const metadata: Metadata = {
  title: "فروشگاه آنلاین",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
        <head>
            <link rel="manifest" href="/manifest.json" />
            <meta name="theme-color" content="#2563eb" />
        </head>
        <body style={{ background: "#f3f4f6 !important" }}>
        <FetchUserClient />
        <Toaster position="top-center" reverseOrder={false} />
        <ThemeWrapper>
                <PWAUpdater />
                <AppVersionChecker />
                {children}
            </ThemeWrapper>
        </body>
        </html>
    );
}
